### ISSUE TITLE
关于多表连接后，查询返回对象仅指定第一张表对应实体，造成后面几张表字段重复填入该对象的问题

### ISSUE THREAD

**Issue by xuse** [GeeQuery/ef-orm#102]
操作者误用方式——
使用使用criteria创建Join A,B,C三个对象后进行查询，
````
session.selectAs(join, A.class);
````
该次查询将会查出A,B,C三表的所有列，并尝试填入对象A中。

API设计中selectAs(join, ResultType.class)中的ResultType可以是任意一个DO/DTO/VO的POJO对象，并非DB专用绑定的Entity。因此会尝试将所有查出的列填写如传入的POJO对象。
实际用法中，用户可以专门编写了一个包含A,B,C所有字段的VO，用来承接三张表的所有字段。

但在上例中，用户仅传入了A.class，其理解是认为传入A类型，就应当只使用A表的返回列，B、C表的返回列应该被丢弃。而实际上，由于B,C表中也包含和A表相同的列（比如A、B、C表都有一个字段 Type），此时出现了映射关系混淆，即框架无法判断用户意图——究竟是哪张表的Type字段需要填入返回结果。

在这个案例中，框架和用户的理解出现了分歧。用户在编写查询时，并未丢弃B、C表的列。框架尽可能的将所有查出列都填写到返回对象中，于是返回结果出现了偏差。

诊断问题后发现，由于框架的不当容错，使得开发者不容易发现自己使用上的问题。实际上，只要抛出了异常，开发者有多种简单的方式解决这一问题——
* 使用Selects.noColumns()方法丢弃查询中不需要的两张表返回列。
* 使用Object[].class作为返回结果的承接对象，用户将得到一个长度为3的，包含了A、B、C三个对象的数组。

为此，取消容错。当出现上述错误用法时，抛出异常——
```
javax.persistence.PersistenceException: Ambiguous column will set to field [type]. Hint: you can use Object[] as a result container to receive multiple tables in this join, or remove unsed select columns in the query.
	at jef.database.wrapper.populator.ResultPopulatorImpl.fill(ResultPopulatorImpl.java:696)
	at jef.database.wrapper.populator.ResultPopulatorImpl.access$2(ResultPopulatorImpl.java:672)
	at jef.database.wrapper.populator.ResultPopulatorImpl$NormalRsIterator.initColumnAccessor(ResultPopulatorImpl.java:544)
```

但是只需要填入A表即可。而B,C表中有部分列名称和A表的列名称一样。

**Comment by xuse** [comment]
修复。
此外，增加异常信息，当从ResultSet中获取对象错误时，显示当时的列名，用以诊断故障和问题。
