### ISSUE TITLE
Version 1.11.4当中，将Boolean在MySQL上的默认映射作为BIT(1)，然后MySQL驱动出BUG了。

### ISSUE THREAD

**Issue by xuse** [GeeQuery/ef-orm#73]
今天测试遇到一个JDBC驱动问题

```
DriverName          MySQL Connector Java
DriverVersion       mysql-connector-java-5.1.39 ( Revision: 3289a357af6d09ecc1a10fd3c26e95183e5790ad ) 5
DatabaseProductName MySQL
DatabaseProductVersion  5.5.42-MariaDB 5
```

当使用悲观锁更新
ResultSet.updateRow()时，抛出

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
    at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
    at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
    at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
    at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2341)
```

经检查，是MySQL驱动在执行悲观锁更新时是通过update 语句进行的，当被更新的字段中有BIT(1)时，数据库抛出上述异常。
其他数据类型无此问题，就是BIT有。而且明显是驱动BUG。
更换MariaDB的驱动，发现不支持悲观锁更新……

**Comment by xuse** [comment]
该问题只能通过数据库设计回避，如果要使用悲观锁，就不能使用BIT(1)作为数据库的字段类型。
