### ISSUE TITLE
SQL语法解析问题

### ISSUE THREAD

**Issue by xuse** [GeeQuery/ef-orm#74]
```
select * from foo where id in :idlist
```

某朋友咨询，该语句解析为什么出错。

```
jef.database.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "id "" at line 1, column 25.
Was expecting one of:
    "(" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    ":" ...
    "(" ...
    "(" ...
    "?" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    "?" ...
    ":" ...
    ":" ...
    "(" ...

    at jef.database.jsqlparser.parser.JpqlParser.generateParseException(JpqlParser.java:6288)
    at jef.database.jsqlparser.parser.JpqlParser.jj_consume_token(JpqlParser.java:6164)
    at jef.database.jsqlparser.parser.JpqlParser.Expression(JpqlParser.java:1620)
    at jef.database.jsqlparser.parser.JpqlParser.WhereClause(JpqlParser.java:1340)
    at jef.database.jsqlparser.parser.JpqlParser.PlainSelect(JpqlParser.java:713)
    at jef.database.jsqlparser.parser.JpqlParser.SelectBody(JpqlParser.java:628)
    at jef.database.jsqlparser.parser.JpqlParser.Select(JpqlParser.java:615)
    at jef.database.jsqlparser.parser.JpqlParser.Statement(JpqlParser.java:94)
```

原因是——

**Comment by xuse** [comment]
解析器认为
in (:idlist)是一个合法的 IN 语句结构，能够识别。用户之前编写的SQL中，漏掉了IN 条件外面的括号。
造成上述错误，并非程序BUG。
正确的写法如下——
````
select * from foo where id in (:idlist)
````
特此记录，
//TODO Document into FAQ
